# Generated by Django 4.1 on 2022-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BhsaNodes',
            fields=[
                ('node', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('otype', models.CharField(max_length=20)),
                ('oslots', models.JSONField(default=list)),
                ('book', models.CharField(max_length=30)),
                ('chapter', models.IntegerField(default=1)),
                ('verse', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BhsaSlots',
            fields=[
                ('node', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
