# Generated by Django 4.1 on 2022-08-29 02:57

from django.db import migrations
from tf.fabric import Fabric

# load BHSA from Text-Fabric
BHSA_DATA_DIR = '/Users/cody/github/etcbc/bhsa/tf/2021'
TF = Fabric(locations=BHSA_DATA_DIR)
bhsa = TF.load('otype book chapter verse')


def fill_nodes(apps, schema_editor):
    """Fill nodes with dummy data."""
    print('FILL NODES START')
    # set up models
    BhsaSlots = apps.get_model('text_carousel', 'BhsaSlots')
    BhsaNodes = apps.get_model('text_carousel', 'BhsaNodes')

    # populate words
    print('Beginning word table...')
    for word in bhsa.F.otype.s('word'):
        this_word = BhsaSlots(
            node=word,
            text=bhsa.T.text(word),
        )
        this_word.save()
    print('Done with word table!')

    # populate all other nodes
    print('Beginning node table...')
    good_otypes = {
        'verse', 'clause', 'phrase',
    }
    for node in bhsa.N.walk():
        otype = bhsa.F.otype.v(node)
        if otype not in good_otypes:
            continue
        book, chapter, verse = bhsa.T.sectionFromNode(node)
        oslots = list(bhsa.L.d(node, 'word'))
        this_oslot = BhsaNodes(
            node=node,
            otype=otype,
            oslots=oslots,
            book=book,
            chapter=chapter,
            verse=verse,
        )
        this_oslot.save()
    print('Done with node table!')


class Migration(migrations.Migration):

    dependencies = [
        ('text_carousel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_nodes),
    ]
